[node_network]
read_limit = 1_000 # Security feature

[node_network.server]
enable_prometheus_server = false
prometheus_port = 8_000
update_interval = 1

[node_network.client]
enable_prometheus_server = false
prometheus_port = 8_000
update_interval = 1
timeout = 5
