version: 1

handlers:
  console:
    class : logging.StreamHandler
    formatter: default
    level   : INFO
    stream  : ext://sys.stdout
  nodes_file:
    class : logging.handlers.RotatingFileHandler
    formatter: json
    level   : DEBUG
    filename: logs/nodes.log
    maxBytes: 2_000_000
    backupCount: 7
  node_client_file:
    class : logging.handlers.RotatingFileHandler
    formatter: json
    level   : DEBUG
    filename: logs/node_client.log
    maxBytes: 2_000_000
    backupCount: 7


formatters:
  default:
    format: '%(asctime)s %(levelname)-8s %(name)-15s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  json:
    class: pythonjsonlogger.jsonlogger.JsonFormatter
    format: '%(asctime)s %(levelname)s %(message)s'

loggers:
  data_node_network.nodes:
    level: DEBUG
    handlers:
      - console
      - nodes_file
  data_node_network.client:
    level: DEBUG
    handlers:
      - console
      - node_client_file